name: lint

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  check:
    runs-on: ubuntu-latest
    name: check 3.10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up CPython 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        id: install-deps
        run: |
          curl -fsSL https://install.python-poetry.org | python3 -
          export PATH=$HOME/.local/bin:$PATH
          poetry config virtualenvs.create false
          poetry install
      
      - name: Run black
        if: ${{ always() && steps.install-deps.outcome == 'success' }}
        run: |
          black --check .
      
      - name: Run isort
        if: ${{ always() && steps.install-deps.outcome == 'success' }}
        run: |
          isort -c .
