name: lint

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.x' ]

    name: check ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      # we install the web extra too so that isort knows what's what
      - name: Install dependencies
        id: install-deps
        run: |
          curl -fsSL https://install.python-poetry.org | python3 -
          export PATH=$HOME/.local/bin:$PATH
          poetry config virtualenvs.create false
          poetry install --with dev,web
      
      - name: Run black
        if: ${{ always() && steps.install-deps.outcome == 'success' }}
        run: |
          black --check .
      
      - name: Run isort
        if: ${{ always() && steps.install-deps.outcome == 'success' }}
        run: |
          isort -p config -c .
